// ---------------------------------------------------------------------------
// TILE MANIFEST — the single source of truth for the block atlas.
//
// Every entry here MUST have a painter registered in src/textures/blocks/*.js,
// and every tile referenced by a block definition MUST appear here. The dev
// harness (tools/verify.mjs) asserts both directions, so a typo can never ship
// as an invisible/among-us texture.
//
// Flags:
//   t : tint index. 1=grass 2=foliage 3=water 0/absent=none.
//       Tinted tiles MUST be painted greyscale-ish (luma carries the detail) so
//       the vertex tint multiply produces the biome colour.
//   a : animation frame count (tile is registered via addAnimated)
//   s : animation speed bucket (index into ANIM_SPEEDS)
//   c : alpha cutout (leaves, plants, glass)
//   g : tile is NOT seamlessly tileable -> pack with edge-clamp instead of wrap
// ---------------------------------------------------------------------------

/** @typedef {{name:string, brief:string, t?:number, a?:number, s?:number, c?:boolean, g?:boolean}} TileSpec */

/** @type {TileSpec[]} */
export const TILE_SPECS = [
  // ---------------------------------------------------------------- terrain
  { name: 'grass_top', brief: 'greyscale grass mat: fine blade noise, 4 shades, slight clumping', t: 1 },
  { name: 'grass_side', brief: 'dirt with a ragged grass fringe over the top 4-6 rows; blades hang down irregularly', g: true },
  { name: 'grass_side_overlay', brief: 'only the grass fringe, alpha below — tinted separately over grass_side', t: 1, c: true, g: true },
  { name: 'dirt', brief: 'brown earth, dense speckle, few small pebbles, 5 shades' },
  { name: 'coarse_dirt', brief: 'dirt but grittier: more dark specks and tiny gravel bits' },
  { name: 'podzol_top', brief: 'dark rust-brown forest floor with orange needle litter' },
  { name: 'mycelium_top', brief: 'pale grey-violet fungal mat, fine mottled pores' },
  { name: 'dirt_path_top', brief: 'compacted pale dirt, faint concentric wear rings' },
  { name: 'dirt_path_side', brief: 'dirt with a thin compacted lighter cap on top 2 rows', g: true },
  { name: 'farmland', brief: 'tilled soil: 4 horizontal furrow ridges with shadow lines', g: true },
  { name: 'farmland_wet', brief: 'farmland darker and glistening, moist furrows', g: true },
  { name: 'stone', brief: 'grey stone, fbm mottle, 5 shades, a couple of hairline cracks' },
  { name: 'cobblestone', brief: 'irregular voronoi stone chunks, dark mortar seams, per-chunk shading' },
  { name: 'mossy_cobblestone', brief: 'cobblestone with green moss creeping in the seams and chunk corners' },
  { name: 'stone_bricks', brief: 'regular brick courses in grey stone, deep mortar, chipped corners' },
  { name: 'cracked_stone_bricks', brief: 'stone bricks with jagged dark cracks running across several bricks' },
  { name: 'mossy_stone_bricks', brief: 'stone bricks with moss patches in the mortar' },
  { name: 'chiseled_stone_bricks', brief: 'stone panel with a carved pillar/eye motif in the centre, framed border' },
  { name: 'smooth_stone', brief: 'flat-ish smooth grey stone with faint horizontal banding and a border' },
  { name: 'deepslate', brief: 'very dark blue-grey rock with vertical streaks and fine banding' },
  { name: 'deepslate_top', brief: 'deepslate seen end-on: tighter concentric streaks' },
  { name: 'cobbled_deepslate', brief: 'deepslate broken into angular chunks with near-black seams' },
  { name: 'deepslate_bricks', brief: 'dark slate brick courses, tight mortar' },
  { name: 'andesite', brief: 'medium grey speckled igneous rock, salt-and-pepper' },
  { name: 'granite', brief: 'pink-brown rock with darker mineral flecks' },
  { name: 'diorite', brief: 'near-white rock with black speckles' },
  { name: 'tuff', brief: 'olive-grey porous rock, blotchy' },
  { name: 'calcite', brief: 'pale cream-white crystalline rock, faint facets' },
  { name: 'gravel', brief: 'loose rounded pebbles of mixed grey/brown, visible individual stones' },
  { name: 'clay', brief: 'pale blue-grey smooth clay with faint mottling' },
  { name: 'sand', brief: 'pale gold, dense fine grain, subtle dune ripple lines' },
  { name: 'red_sand', brief: 'orange-red sand grain, same ripple structure' },
  { name: 'sandstone_top', brief: 'sand grain compacted, faint concentric rings' },
  { name: 'sandstone', brief: 'horizontal sedimentary strata bands in pale gold, grain within bands' },
  { name: 'sandstone_bottom', brief: 'coarser sandstone, heavier grain' },
  { name: 'chiseled_sandstone', brief: 'sandstone panel with a carved creeper-ish glyph and framed border' },
  { name: 'cut_sandstone', brief: 'sandstone split into 4 smooth quadrant blocks with seams' },
  { name: 'red_sandstone_top', brief: 'red sand compacted rings' },
  { name: 'red_sandstone', brief: 'red sedimentary strata bands' },
  { name: 'red_sandstone_bottom', brief: 'coarse red sandstone' },
  { name: 'terracotta', brief: 'plain fired clay, muted orange-brown, faint horizontal wash' },
  { name: 'white_terracotta', brief: 'off-white fired clay band, faint speckle' },
  { name: 'orange_terracotta', brief: 'burnt orange fired clay band' },
  { name: 'yellow_terracotta', brief: 'ochre fired clay band' },
  { name: 'red_terracotta', brief: 'deep brick-red fired clay band' },
  { name: 'brown_terracotta', brief: 'dark chocolate fired clay band' },
  { name: 'light_gray_terracotta', brief: 'grey-mauve fired clay band' },
  { name: 'snow', brief: 'near-white with faint blue-grey dimples and sparkle pixels' },
  { name: 'snow_side', brief: 'snow cap over a thin dirt strip at the bottom', g: true },
  { name: 'ice', brief: 'translucent pale blue with long diagonal fracture lines and a specular streak' },
  { name: 'packed_ice', brief: 'denser blue ice, tighter fractures, less transparent look' },
  { name: 'blue_ice', brief: 'saturated deep cyan ice, smooth with bright highlights' },
  { name: 'obsidian', brief: 'near-black volcanic glass with faint purple sheen streaks and sharp facets' },
  { name: 'crying_obsidian', brief: 'obsidian with glowing magenta teardrop veins' },
  { name: 'bedrock', brief: 'chaotic dark grey blocky rubble, very high contrast' },

  // ---------------------------------------------------------------- ores
  { name: 'coal_ore', brief: 'stone base with 4-5 matte black coal blobs, dark rims' },
  { name: 'iron_ore', brief: 'stone base with tan-pink iron blobs, lighter top-left lit edge' },
  { name: 'copper_ore', brief: 'stone base with teal-orange copper blobs' },
  { name: 'gold_ore', brief: 'stone base with bright yellow-gold blobs and a sparkle pixel each' },
  { name: 'redstone_ore', brief: 'stone base with crimson red blobs, slight inner glow' },
  { name: 'lapis_ore', brief: 'stone base with deep royal-blue blobs, some lighter flecks' },
  { name: 'diamond_ore', brief: 'stone base with cyan crystal blobs, faceted with white highlights' },
  { name: 'emerald_ore', brief: 'stone base with vivid green crystal blobs' },
  { name: 'deepslate_coal_ore', brief: 'deepslate base, black coal blobs' },
  { name: 'deepslate_iron_ore', brief: 'deepslate base, tan iron blobs' },
  { name: 'deepslate_copper_ore', brief: 'deepslate base, teal copper blobs' },
  { name: 'deepslate_gold_ore', brief: 'deepslate base, gold blobs' },
  { name: 'deepslate_redstone_ore', brief: 'deepslate base, red blobs' },
  { name: 'deepslate_lapis_ore', brief: 'deepslate base, blue blobs' },
  { name: 'deepslate_diamond_ore', brief: 'deepslate base, cyan crystal blobs' },
  { name: 'deepslate_emerald_ore', brief: 'deepslate base, green crystal blobs' },
  { name: 'nether_gold_ore', brief: 'netherrack base with gold flecks' },
  { name: 'nether_quartz_ore', brief: 'netherrack base with white quartz blobs' },
  { name: 'ancient_debris_top', brief: 'dark brown-grey metal with a warped netherite swirl core' },
  { name: 'ancient_debris_side', brief: 'dark scorched metal slab with brown crust bands' },

  // ---------------------------------------------------------------- metal blocks
  { name: 'coal_block', brief: 'solid packed coal, faceted black chunks with grey rims' },
  { name: 'iron_block', brief: 'brushed pale metal with a raised centre square and rivets' },
  { name: 'gold_block', brief: 'polished gold plates with bright bevel highlights' },
  { name: 'diamond_block', brief: 'cyan cut gems arranged in a lattice with white sparkles' },
  { name: 'emerald_block', brief: 'green cut gems lattice with facet highlights' },
  { name: 'lapis_block', brief: 'deep blue mineral mass with lighter blue flecks in a rough grid' },
  { name: 'redstone_block', brief: 'dark red ore mass, fine crimson granules, slight glow' },
  { name: 'copper_block', brief: 'orange-pink hammered metal plates' },
  { name: 'netherite_block', brief: 'very dark metal with purple-brown mottling and hard highlights' },
  { name: 'quartz_block', brief: 'clean white quartz with faint vertical grain' },
  { name: 'bricks', brief: 'classic red clay bricks, pale mortar, per-brick shade variation' },

  // ---------------------------------------------------------------- wood
  { name: 'oak_log', brief: 'medium brown vertical bark strips with dark fissures', g: true },
  { name: 'oak_log_top', brief: 'concentric growth rings, tan, bark rim' },
  { name: 'oak_planks', brief: '4 horizontal planks, warm tan, wood grain lines, dark seams and nail dots' },
  { name: 'oak_leaves', brief: 'greyscale dense leaf clusters with alpha gaps at the edges', t: 2, c: true },
  { name: 'birch_log', brief: 'white bark with black horizontal dashes and knots', g: true },
  { name: 'birch_log_top', brief: 'pale cream rings' },
  { name: 'birch_planks', brief: 'very pale cream planks, fine grain' },
  { name: 'birch_leaves', brief: 'greyscale lighter airier leaf clusters', t: 2, c: true },
  { name: 'spruce_log', brief: 'dark grey-brown bark, deep vertical fissures', g: true },
  { name: 'spruce_log_top', brief: 'dark brown tight rings' },
  { name: 'spruce_planks', brief: 'dark chocolate planks, strong grain' },
  { name: 'spruce_leaves', brief: 'greyscale needle clusters, spiky silhouette', t: 2, c: true },
  { name: 'jungle_log', brief: 'olive-brown bark with mossy patches', g: true },
  { name: 'jungle_log_top', brief: 'orange-tan rings' },
  { name: 'jungle_planks', brief: 'reddish-orange planks' },
  { name: 'jungle_leaves', brief: 'greyscale big broad leaves, dense', t: 2, c: true },
  { name: 'acacia_log', brief: 'grey bark with orange under-tones, cracked plates', g: true },
  { name: 'acacia_log_top', brief: 'orange-red rings' },
  { name: 'acacia_planks', brief: 'orange planks' },
  { name: 'acacia_leaves', brief: 'greyscale flat-topped sparse leaves', t: 2, c: true },
  { name: 'dark_oak_log', brief: 'very dark brown bark, coarse plates', g: true },
  { name: 'dark_oak_log_top', brief: 'dark rings' },
  { name: 'dark_oak_planks', brief: 'deep brown planks' },
  { name: 'dark_oak_leaves', brief: 'greyscale very dark dense leaves', t: 2, c: true },
  { name: 'bookshelf', brief: 'plank frame top/bottom with two shelves of multicoloured book spines', g: true },
  { name: 'crafting_table_top', brief: 'plank surface with a 2x2 grid of dark tool-marked squares' },
  { name: 'crafting_table_side', brief: 'planks with a saw and hammer silhouette hanging', g: true },
  { name: 'crafting_table_front', brief: 'planks with a drawer line and knob plus grid marks', g: true },
  { name: 'chest_front', brief: 'wood chest face: plank body, dark iron latch plate in the middle, band edges', g: true },
  { name: 'chest_side', brief: 'plank chest side with iron corner bands', g: true },
  { name: 'chest_top', brief: 'plank lid with iron hinge bands at the back', g: true },
  { name: 'barrel_top', brief: 'circular barrel lid, radial staves, iron hoop ring' },
  { name: 'barrel_side', brief: 'vertical barrel staves with two iron hoops', g: true },
  { name: 'ladder', brief: 'two vertical rails with 5 rungs, alpha everywhere else', c: true, g: true },
  { name: 'oak_door_top', brief: 'upper door half: planks with a 4-pane window and iron hinges', c: true, g: true },
  { name: 'oak_door_bottom', brief: 'lower door half: vertical planks, iron hinge plates, handle', c: true, g: true },
  { name: 'iron_door_top', brief: 'metal upper door with barred window slit', c: true, g: true },
  { name: 'iron_door_bottom', brief: 'riveted metal lower door panel', c: true, g: true },
  { name: 'oak_trapdoor', brief: 'plank hatch with iron strap hinges', c: true, g: true },
  { name: 'hay_block_top', brief: 'bundled straw cross-section, radial stalks, twine ring' },
  { name: 'hay_block_side', brief: 'horizontal straw bundle with two twine bands', g: true },
  { name: 'mushroom_stem', brief: 'pale cream fibrous stem, vertical strands', g: true },
  { name: 'red_mushroom_block', brief: 'deep red cap with big white oval spots' },
  { name: 'brown_mushroom_block', brief: 'brown cap, faint mottling' },
  { name: 'mushroom_block_inside', brief: 'pale spongy fungus flesh' },

  // ---------------------------------------------------------------- plants
  { name: 'oak_sapling', brief: 'tiny two-leaf sapling on a thin stem, alpha bg', t: 2, c: true, g: true },
  { name: 'birch_sapling', brief: 'pale small sapling, alpha bg', t: 2, c: true, g: true },
  { name: 'spruce_sapling', brief: 'small conifer sapling, alpha bg', t: 2, c: true, g: true },
  { name: 'jungle_sapling', brief: 'broad-leaf sapling, alpha bg', t: 2, c: true, g: true },
  { name: 'acacia_sapling', brief: 'thin flat-top sapling, alpha bg', t: 2, c: true, g: true },
  { name: 'dark_oak_sapling', brief: 'dark bushy sapling, alpha bg', t: 2, c: true, g: true },
  { name: 'tall_grass', brief: 'greyscale clump of 6-8 grass blades of varying height, alpha bg', t: 1, c: true, g: true },
  { name: 'fern', brief: 'greyscale fern frond pair, alpha bg', t: 1, c: true, g: true },
  { name: 'large_fern_top', brief: 'greyscale upper fern fronds, alpha bg', t: 1, c: true, g: true },
  { name: 'large_fern_bottom', brief: 'greyscale lower fern stalks, alpha bg', t: 1, c: true, g: true },
  { name: 'dead_bush', brief: 'brittle brown twig cluster, alpha bg', c: true, g: true },
  { name: 'dandelion', brief: 'yellow flower head on green stem with leaves, alpha bg', c: true, g: true },
  { name: 'poppy', brief: 'red 4-petal flower with dark centre, green stem, alpha bg', c: true, g: true },
  { name: 'blue_orchid', brief: 'cyan-blue orchid spray, alpha bg', c: true, g: true },
  { name: 'allium', brief: 'magenta pompom head on tall stem, alpha bg', c: true, g: true },
  { name: 'azure_bluet', brief: 'small white daisies with yellow centres, alpha bg', c: true, g: true },
  { name: 'red_tulip', brief: 'red tulip cup on stem with long leaves, alpha bg', c: true, g: true },
  { name: 'orange_tulip', brief: 'orange tulip cup, alpha bg', c: true, g: true },
  { name: 'white_tulip', brief: 'white tulip cup, alpha bg', c: true, g: true },
  { name: 'pink_tulip', brief: 'pink tulip cup, alpha bg', c: true, g: true },
  { name: 'oxeye_daisy', brief: 'white petal ring with yellow centre, alpha bg', c: true, g: true },
  { name: 'cornflower', brief: 'ragged blue-violet bloom, alpha bg', c: true, g: true },
  { name: 'lily_of_the_valley', brief: 'string of tiny white bells on an arching stem, alpha bg', c: true, g: true },
  { name: 'sunflower_top', brief: 'big yellow petal disc with brown seed centre, alpha bg', c: true, g: true },
  { name: 'sunflower_bottom', brief: 'thick green stalk with two broad leaves, alpha bg', c: true, g: true },
  { name: 'rose_bush_top', brief: 'cluster of dark red roses among leaves, alpha bg', c: true, g: true },
  { name: 'rose_bush_bottom', brief: 'thorny stems and leaves, alpha bg', c: true, g: true },
  { name: 'brown_mushroom', brief: 'small brown domed mushroom, pale stem, alpha bg', c: true, g: true },
  { name: 'red_mushroom', brief: 'red spotted mushroom, pale stem, alpha bg', c: true, g: true },
  { name: 'wheat_0', brief: 'just-sprouted seedlings, tiny green shoots, alpha bg', c: true, g: true },
  { name: 'wheat_1', brief: 'short green shoots, alpha bg', c: true, g: true },
  { name: 'wheat_2', brief: 'taller green stalks, alpha bg', c: true, g: true },
  { name: 'wheat_3', brief: 'green stalks with first heads, alpha bg', c: true, g: true },
  { name: 'wheat_4', brief: 'stalks yellowing at the tips, alpha bg', c: true, g: true },
  { name: 'wheat_5', brief: 'half-golden stalks with grain heads, alpha bg', c: true, g: true },
  { name: 'wheat_6', brief: 'mostly golden heavy heads, alpha bg', c: true, g: true },
  { name: 'wheat_7', brief: 'fully ripe golden wheat, drooping heads, alpha bg', c: true, g: true },
  { name: 'carrots_0', brief: 'small carrot leaf sprigs, alpha bg', c: true, g: true },
  { name: 'carrots_1', brief: 'carrot foliage, alpha bg', c: true, g: true },
  { name: 'carrots_2', brief: 'fuller carrot foliage, alpha bg', c: true, g: true },
  { name: 'carrots_3', brief: 'carrot tops with orange crowns showing, alpha bg', c: true, g: true },
  { name: 'potatoes_0', brief: 'small potato sprigs, alpha bg', c: true, g: true },
  { name: 'potatoes_1', brief: 'potato foliage, alpha bg', c: true, g: true },
  { name: 'potatoes_2', brief: 'fuller potato plant, alpha bg', c: true, g: true },
  { name: 'potatoes_3', brief: 'potato plant with small flowers, alpha bg', c: true, g: true },
  { name: 'beetroots_0', brief: 'beet seedlings, alpha bg', c: true, g: true },
  { name: 'beetroots_1', brief: 'beet leaves, alpha bg', c: true, g: true },
  { name: 'beetroots_2', brief: 'larger red-veined beet leaves, alpha bg', c: true, g: true },
  { name: 'beetroots_3', brief: 'ripe beet crowns pushing out of soil, alpha bg', c: true, g: true },
  { name: 'cactus_top', brief: 'green cactus crown, concentric ribs, tiny areole spines' },
  { name: 'cactus_side', brief: 'green cactus flesh with vertical ribs and pale spine pairs', g: true },
  { name: 'cactus_bottom', brief: 'cut cactus base, pale green core ring' },
  { name: 'sugar_cane', brief: 'tall pale-green jointed cane stalks, alpha bg', t: 1, c: true, g: true },
  { name: 'bamboo_stalk', brief: 'thin bright green bamboo culm with dark node rings, alpha bg', c: true, g: true },
  { name: 'vine', brief: 'greyscale hanging tendrils with small leaves, mostly alpha', t: 2, c: true, g: true },
  { name: 'lily_pad', brief: 'greyscale round pad with a notch and radial veins, alpha bg', t: 2, c: true, g: true },
  { name: 'seagrass', brief: 'greyscale slender underwater blades, alpha bg', t: 2, c: true, g: true },
  { name: 'kelp', brief: 'greyscale broad kelp blade with a wavy edge, alpha bg', t: 2, c: true, g: true },
  { name: 'pumpkin_top', brief: 'orange pumpkin lid, radial ribs, green stem nub in the middle' },
  { name: 'pumpkin_side', brief: 'orange pumpkin ribs, vertical grooves with shading', g: true },
  { name: 'carved_pumpkin', brief: 'pumpkin side with a triangular-eye jack-o-lantern face cut dark', g: true },
  { name: 'jack_o_lantern', brief: 'carved pumpkin face glowing bright yellow from inside', g: true },
  { name: 'melon_top', brief: 'green melon rind top with faint stripes' },
  { name: 'melon_side', brief: 'green melon with darker vertical stripe bands', g: true },
  { name: 'nether_wart_block', brief: 'dense dark red fungal mass, bumpy pores' },
  { name: 'nether_wart_2', brief: 'red wart sprigs on a stalk, alpha bg', c: true, g: true },
  { name: 'sponge', brief: 'porous yellow sponge, irregular dark holes' },
  { name: 'cobweb', brief: 'white radial spiderweb strands, mostly alpha', c: true, g: true },

  // ---------------------------------------------------------------- glass / light
  { name: 'glass', brief: 'mostly transparent with a bright 1px highlight frame and a diagonal specular streak', c: true, g: true },
  { name: 'glass_pane_top', brief: 'thin glass edge strip, transparent middle', c: true, g: true },
  { name: 'torch', brief: 'thin wooden stick with a bright orange-white flame blob at the top, alpha bg', c: true, g: true },
  { name: 'soul_torch', brief: 'stick with a cyan-blue flame blob, alpha bg', c: true, g: true },
  { name: 'lantern', brief: 'iron cage lantern with a warm glowing core, alpha bg', c: true, g: true },
  { name: 'glowstone', brief: 'crusty yellow-white mineral with bright hot cores and dark rims' },
  { name: 'sea_lantern', brief: 'prismarine frame with a cyan-white glowing crystal centre' },
  { name: 'magma_block', brief: 'dark basalt crust with an orange-red glowing crack lattice', a: 4, s: 4 },
  { name: 'spawner', brief: 'dark iron cage bars over a black void, mostly alpha in the openings', c: true, g: true },
  { name: 'tnt_top', brief: 'red TNT lid with a dark fuse hole in the middle' },
  { name: 'tnt_side', brief: 'red block with a white TNT label band across the middle', g: true },
  { name: 'tnt_bottom', brief: 'red block, plain crate base with slats' },

  // ---------------------------------------------------------------- fluids (animated)
  { name: 'water_still', brief: 'greyscale rippling water: interlocking wave crests, animated by vertical scroll', t: 3, a: 8, s: 1 },
  { name: 'water_flow', brief: 'greyscale downward-streaming water strands', t: 3, a: 8, s: 3 },
  { name: 'lava_still', brief: 'molten orange-yellow with dark crust islands and bright hot spots, animated', a: 8, s: 4 },
  { name: 'lava_flow', brief: 'downward flowing lava with bright leading edges', a: 8, s: 1 },
  { name: 'fire', brief: 'layered orange-yellow flame tongues, alpha bg, animated flicker', a: 8, s: 5, c: true, g: true },
  { name: 'nether_portal', brief: 'violet swirling portal energy, animated, semi-transparent', a: 8, s: 1 },
  { name: 'end_portal', brief: 'black void with tiny starfield sparkles, animated', a: 8, s: 4 },

  // ---------------------------------------------------------------- nether
  { name: 'netherrack', brief: 'dark red porous rock, blotchy with darker pits and lighter crusts' },
  { name: 'soul_sand', brief: 'brown-grey sand with faint anguished face impressions pressed into it' },
  { name: 'soul_soil', brief: 'darker soul dirt, coarse and cracked' },
  { name: 'nether_bricks', brief: 'dark maroon brick courses with near-black mortar' },
  { name: 'red_nether_bricks', brief: 'blood-red brick courses' },
  { name: 'basalt_top', brief: 'grey basalt column cross-section, hexagonal facets' },
  { name: 'basalt_side', brief: 'vertical basalt column striations, grey-brown', g: true },
  { name: 'blackstone', brief: 'very dark grey-black volcanic rock, angular chunks' },
  { name: 'gilded_blackstone', brief: 'blackstone with embedded gold nugget flecks' },
  { name: 'polished_blackstone_bricks', brief: 'black brick courses, tight seams' },
  { name: 'glowstone_dust_block', brief: 'compacted glowing yellow dust, soft speckle' },

  // ---------------------------------------------------------------- end / prismarine
  { name: 'end_stone', brief: 'pale yellow-white rock with grey pitting, slightly bone-like' },
  { name: 'end_stone_bricks', brief: 'pale end stone brick lattice with a fine chiselled pattern' },
  { name: 'purpur_block', brief: 'mauve-violet stone with a fine speckled grain' },
  { name: 'purpur_pillar_top', brief: 'purpur column end, concentric ring' },
  { name: 'purpur_pillar_side', brief: 'purpur column with vertical flutes', g: true },
  { name: 'end_portal_frame_top', brief: 'green-teal stone frame top with a socket for the eye' },
  { name: 'end_portal_frame_side', brief: 'green-teal carved frame side with runes', g: true },
  { name: 'dragon_egg', brief: 'black egg with violet speckles and a soft inner glow', g: true },
  { name: 'prismarine', brief: 'teal-green stone in small irregular tiles, subtle shimmer' },
  { name: 'prismarine_bricks', brief: 'teal brick courses, cleaner geometry' },
  { name: 'dark_prismarine', brief: 'deep blue-green stone, fine grid, darker mortar' },

  // ---------------------------------------------------------------- wool (16)
  { name: 'white_wool', brief: 'soft fibrous wool weave, off-white, visible fuzz' },
  { name: 'orange_wool', brief: 'orange wool weave' },
  { name: 'magenta_wool', brief: 'magenta wool weave' },
  { name: 'light_blue_wool', brief: 'light blue wool weave' },
  { name: 'yellow_wool', brief: 'yellow wool weave' },
  { name: 'lime_wool', brief: 'lime green wool weave' },
  { name: 'pink_wool', brief: 'pink wool weave' },
  { name: 'gray_wool', brief: 'dark grey wool weave' },
  { name: 'light_gray_wool', brief: 'light grey wool weave' },
  { name: 'cyan_wool', brief: 'cyan wool weave' },
  { name: 'purple_wool', brief: 'purple wool weave' },
  { name: 'blue_wool', brief: 'blue wool weave' },
  { name: 'brown_wool', brief: 'brown wool weave' },
  { name: 'green_wool', brief: 'green wool weave' },
  { name: 'red_wool', brief: 'red wool weave' },
  { name: 'black_wool', brief: 'near-black wool weave' },

  // ---------------------------------------------------------------- furniture / misc
  { name: 'furnace_front', brief: 'stone block with a dark arched firebox opening and a grate', g: true },
  { name: 'furnace_front_lit', brief: 'furnace front with the firebox glowing orange and visible embers', g: true },
  { name: 'furnace_side', brief: 'plain cobble-ish stone furnace side with a faint seam', g: true },
  { name: 'furnace_top', brief: 'stone top with a round dark hole rim' },
  { name: 'iron_bars', brief: 'vertical iron bars with a horizontal tie, alpha between', c: true, g: true },
  { name: 'chain', brief: 'vertical interlocking chain links, alpha bg', c: true, g: true },
  { name: 'bed_top_head', brief: 'red quilt with a white pillow at the head end', g: true },
  { name: 'bed_top_foot', brief: 'red quilt with fold lines', g: true },
  { name: 'bed_side', brief: 'wood frame with red mattress edge above it', g: true },
  { name: 'cauldron_top', brief: 'iron rim with dark water inside' },
  { name: 'cauldron_side', brief: 'riveted iron cauldron wall with legs hinted at the bottom', g: true },
  { name: 'rail', brief: 'two metal rails on wooden sleepers, alpha at the edges', c: true, g: true },
  { name: 'campfire_log', brief: 'crossed logs with glowing embers between them', g: true },
  { name: 'flower_pot', brief: 'terracotta pot with a rim and dirt inside, alpha bg', c: true, g: true },
  { name: 'break_placeholder', brief: 'unused - crack overlays are generated separately in crackOverlay.js' },
];

/** Fast lookups built once. */
export const TILE_BY_NAME = new Map(TILE_SPECS.map((s) => [s.name, s]));

export function tileSpec(name) {
  const s = TILE_BY_NAME.get(name);
  if (!s) throw new Error(`tiles.js: no spec for tile '${name}'`);
  return s;
}

/** All tile names that are biome-tinted, by tint index. */
export function tintedTiles(idx) {
  return TILE_SPECS.filter((s) => (s.t || 0) === idx).map((s) => s.name);
}
