// ---------------------------------------------------------------------------
// Passive mob definitions — group B
// All top-level names prefixed MOBDEF_PB_ for concatenation safety.
// ---------------------------------------------------------------------------

export const MOB_DEFS_PASSIVEB = [

  // ---- CAT -----------------------------------------------------------------
  {
    id: 'cat',
    category: 'passive',
    model: 'cat',
    skin: 'cat',
    variants: 11,
    health: 10, armor: 0,
    width: 0.6, height: 0.7,
    speed: 0.3,
    attack: null,
    followRange: 16, xp: [1, 3],
    drops: [
      { item: 'string', min: 0, max: 2 },
    ],
    spawn: {
      dimension: 'overworld',
      biomes: ['plains', 'forest', 'swamp'],
      light: 'day', where: 'surface',
      weight: 5, group: [1, 2], maxPerChunk: 2, cap: 'passive',
    },
    ai: ['wander', 'lookAround', 'sit', 'followOwner', 'breed:cod', 'growUp', 'followParent', 'tempt'],
    sounds: { idle: 'catIdle', hurt: 'catHurt', death: 'catDeath', step: 'stepSoft', purr: 'catPurr' },
    tameable: { item: 'cod', chance: 0.33 },
    rideable: false, breedItem: 'cod', babyScale: 0.5,
    fireImmune: false, waterMob: false, flying: false, avoidsSun: false,
    special: null,
  },

  // ---- OCELOT --------------------------------------------------------------
  {
    id: 'ocelot',
    category: 'passive',
    model: 'ocelot',
    skin: 'ocelot',
    variants: 1,
    health: 10, armor: 0,
    width: 0.6, height: 0.7,
    speed: 0.3,
    attack: null,
    followRange: 16, xp: [1, 3],
    drops: [],
    spawn: {
      dimension: 'overworld',
      biomes: ['jungle'],
      light: 'day', where: 'surface',
      weight: 4, group: [1, 2], maxPerChunk: 2, cap: 'passive',
    },
    ai: ['wander', 'lookAround', 'panic', 'tempt', 'fleeFrom'],
    sounds: { idle: 'catIdle', hurt: 'catHurt', death: 'catDeath', step: 'stepSoft' },
    tameable: null,
    rideable: false, breedItem: null, babyScale: 0.5,
    fireImmune: false, waterMob: false, flying: false, avoidsSun: false,
    special: null,
  },

  // ---- WOLF ----------------------------------------------------------------
  {
    id: 'wolf',
    category: 'neutral',
    model: 'wolf',
    skin: 'wolf',
    variants: 1,
    health: 8, armor: 0,
    width: 0.6, height: 0.85,
    speed: 0.3,
    attack: { damage: 4, range: 1.5, cooldown: 20 },
    followRange: 16, xp: [1, 3],
    drops: [],
    spawn: {
      dimension: 'overworld',
      biomes: ['forest', 'snowy_taiga'],
      light: 'day', where: 'surface',
      weight: 6, group: [2, 4], maxPerChunk: 4, cap: 'passive',
    },
    ai: ['wander', 'lookAround', 'sit', 'followOwner', 'meleeAttack', 'breed:bone', 'growUp', 'followParent', 'tempt'],
    sounds: { idle: 'wolfIdle', hurt: 'wolfHurt', death: 'wolfDeath', step: 'stepSoft', howl: 'wolfHowl' },
    tameable: { item: 'bone', chance: 0.33 },
    rideable: false, breedItem: 'bone', babyScale: 0.5,
    fireImmune: false, waterMob: false, flying: false, avoidsSun: false,
    special: null,
  },

  // ---- PARROT --------------------------------------------------------------
  {
    id: 'parrot',
    category: 'passive',
    model: 'parrot',
    skin: 'parrot',
    variants: 5,
    health: 6, armor: 0,
    width: 0.5, height: 0.9,
    speed: 0.4,
    attack: null,
    followRange: 16, xp: [1, 3],
    drops: [
      { item: 'feather', min: 1, max: 2 },
    ],
    spawn: {
      dimension: 'overworld',
      biomes: ['jungle'],
      light: 'day', where: 'surface',
      weight: 6, group: [1, 2], maxPerChunk: 2, cap: 'passive',
    },
    ai: ['wander', 'lookAround', 'followOwner', 'tempt'],
    sounds: { idle: 'parrotIdle', hurt: 'parrotHurt', death: 'parrotDeath', step: 'stepSoft' },
    tameable: { item: 'wheat_seeds', chance: 0.33 },
    rideable: false, breedItem: null, babyScale: 0.5,
    fireImmune: false, waterMob: false, flying: true, avoidsSun: false,
    special: null,
  },

  // ---- FOX -----------------------------------------------------------------
  {
    id: 'fox',
    category: 'passive',
    model: 'fox',
    skin: 'fox',
    variants: 2, // 0=red, 1=arctic
    health: 10, armor: 0,
    width: 0.6, height: 0.7,
    speed: 0.3,
    attack: { damage: 2, range: 1.5, cooldown: 20 },
    followRange: 16, xp: [1, 3],
    drops: [],
    spawn: {
      dimension: 'overworld',
      biomes: ['forest', 'snowy_taiga'],
      light: 'night', where: 'surface',
      weight: 3, group: [1, 2], maxPerChunk: 2, cap: 'passive',
    },
    ai: ['wander', 'lookAround', 'breed:sweet_berries', 'growUp', 'followParent', 'meleeAttack', 'tempt'],
    sounds: { idle: 'foxIdle', hurt: 'foxHurt', death: 'foxDeath', step: 'stepSoft' },
    tameable: null,
    rideable: false, breedItem: 'sweet_berries', babyScale: 0.5,
    fireImmune: false, waterMob: false, flying: false, avoidsSun: false,
    special: null,
  },

  // ---- BEE -----------------------------------------------------------------
  {
    id: 'bee',
    category: 'neutral',
    model: 'bee',
    skin: 'bee',
    variants: 1,
    health: 10, armor: 0,
    width: 0.7, height: 0.6,
    speed: 0.3,
    attack: { damage: 2, range: 0.8, cooldown: 20 },
    followRange: 16, xp: [1, 3],
    drops: [
      { item: 'honeycomb', min: 0, max: 1 },
    ],
    spawn: {
      dimension: 'overworld',
      biomes: ['plains', 'forest', 'jungle', 'savanna'],
      light: 'day', where: 'air',
      weight: 4, group: [1, 3], maxPerChunk: 3, cap: 'passive',
    },
    ai: ['wander', 'lookAround', 'pollinate', 'meleeAttack', 'breed:poppy', 'growUp', 'followParent', 'goToLove'],
    sounds: { idle: 'beeIdle', hurt: 'beeHurt', death: 'beeDeath', step: 'stepSoft', sting: 'beeSting' },
    tameable: null,
    rideable: false, breedItem: 'poppy', babyScale: 0.5,
    fireImmune: false, waterMob: false, flying: true, avoidsSun: false,
    special: 'bee',
  },

  // ---- TURTLE --------------------------------------------------------------
  {
    id: 'turtle',
    category: 'passive',
    model: 'turtle',
    skin: 'turtle',
    variants: 1,
    health: 30, armor: 0,
    width: 1.2, height: 0.4,
    speed: 0.12,
    attack: null,
    followRange: 16, xp: [1, 3],
    drops: [
      { item: 'scute', min: 0, max: 1 },
    ],
    spawn: {
      dimension: 'overworld',
      biomes: ['beach', 'swamp'],
      light: 'day', where: 'surface',
      weight: 6, group: [2, 4], maxPerChunk: 4, cap: 'passive',
    },
    ai: ['wander', 'lookAround', 'swim', 'breed:seagrass', 'growUp', 'followParent', 'tempt'],
    sounds: { idle: 'turtleIdle', hurt: 'turtleHurt', death: 'turtleDeath', step: 'stepSoft' },
    tameable: null,
    rideable: false, breedItem: 'seagrass', babyScale: 0.3,
    fireImmune: false, waterMob: false, flying: false, avoidsSun: false,
    special: null,
  },

  // ---- GOAT ----------------------------------------------------------------
  {
    id: 'goat',
    category: 'neutral',
    model: 'goat',
    skin: 'goat',
    variants: 1,
    health: 10, armor: 0,
    width: 0.9, height: 1.3,
    speed: 0.2,
    attack: { damage: 2, range: 1.5, cooldown: 20 },
    followRange: 16, xp: [1, 3],
    drops: [
      { item: 'mutton', min: 1, max: 2, cookedItem: 'cooked_mutton' },
    ],
    spawn: {
      dimension: 'overworld',
      biomes: ['mountains'],
      light: 'day', where: 'surface',
      weight: 8, group: [2, 4], maxPerChunk: 4, cap: 'passive',
    },
    ai: ['wander', 'lookAround', 'panic', 'followPlayerHolding:wheat', 'breed:wheat', 'growUp', 'followParent', 'chargeAttack'],
    sounds: { idle: 'goatIdle', hurt: 'goatHurt', death: 'goatDeath', step: 'stepHard', bleat: 'goatBleat' },
    tameable: null,
    rideable: false, breedItem: 'wheat', babyScale: 0.5,
    fireImmune: false, waterMob: false, flying: false, avoidsSun: false,
    special: 'goat',
  },

  // ---- SNIFFER -------------------------------------------------------------
  {
    id: 'sniffer',
    category: 'passive',
    model: 'sniffer',
    skin: 'sniffer',
    variants: 1,
    health: 14, armor: 0,
    width: 1.9, height: 1.75,
    speed: 0.1,
    attack: null,
    followRange: 16, xp: [5, 8],
    drops: [],
    spawn: null, // never naturally spawns; hatched from sniffer egg
    ai: ['wander', 'lookAround', 'breed:wheat_seeds', 'growUp', 'followParent', 'digIn'],
    sounds: { idle: 'snifferIdle', hurt: 'snifferHurt', death: 'snifferDeath', step: 'stepHard', sniff: 'snifferSniff' },
    tameable: null,
    rideable: false, breedItem: 'wheat_seeds', babyScale: 0.5, // torchflower_seeds not in items.js; wheat_seeds used
    fireImmune: false, waterMob: false, flying: false, avoidsSun: false,
    special: null,
  },

  // ---- CAMEL ---------------------------------------------------------------
  {
    id: 'camel',
    category: 'passive',
    model: 'camel',
    skin: 'camel',
    variants: 1,
    health: 32, armor: 0,
    width: 0.9, height: 2.375,
    speed: 0.09,
    attack: null,
    followRange: 16, xp: [1, 3],
    drops: [],
    spawn: {
      dimension: 'overworld',
      biomes: ['desert'],
      light: 'day', where: 'surface',
      weight: 3, group: [1, 2], maxPerChunk: 2, cap: 'passive',
    },
    ai: ['wander', 'lookAround', 'followPlayerHolding:cactus', 'breed:cactus', 'growUp', 'followParent', 'rideBoost'],
    sounds: { idle: 'camelIdle', hurt: 'camelHurt', death: 'camelDeath', step: 'stepHard' },
    tameable: null,
    rideable: true, breedItem: 'cactus', babyScale: 0.5,
    fireImmune: false, waterMob: false, flying: false, avoidsSun: false,
    special: null,
  },

  // ---- ARMADILLO -----------------------------------------------------------
  {
    id: 'armadillo',
    category: 'passive',
    model: 'armadillo',
    skin: 'armadillo',
    variants: 1,
    health: 12, armor: 0,
    width: 0.7, height: 0.6,
    speed: 0.14,
    attack: null,
    followRange: 16, xp: [1, 3],
    drops: [
      { item: 'scute', min: 0, max: 1 }, // armadillo_scute not in items.js; using scute
    ],
    spawn: {
      dimension: 'overworld',
      biomes: ['savanna', 'badlands'],
      light: 'day', where: 'surface',
      weight: 5, group: [1, 3], maxPerChunk: 3, cap: 'passive',
    },
    ai: ['wander', 'lookAround', 'panic', 'fleeFrom', 'custom:armadillo'],
    sounds: { idle: 'armadilloIdle', hurt: 'armadilloHurt', death: 'armadilloDeath', step: 'stepSoft' },
    tameable: null,
    rideable: false, breedItem: null, babyScale: 0.5,
    fireImmune: false, waterMob: false, flying: false, avoidsSun: false,
    special: null,
  },

  // ---- BAT -----------------------------------------------------------------
  {
    id: 'bat',
    category: 'passive',
    model: 'bat',
    skin: 'bat',
    variants: 1,
    health: 6, armor: 0,
    width: 0.5, height: 0.9,
    speed: 0.6,
    attack: null,
    followRange: 16, xp: [0, 0],
    drops: [],
    spawn: {
      dimension: 'overworld',
      biomes: 'any',
      light: 'dark', where: 'cave',
      weight: 10, group: [2, 8], maxPerChunk: 8, cap: 'ambient',
    },
    ai: ['wander', 'lookAround'],
    sounds: { idle: 'batIdle', hurt: 'batHurt', death: 'batDeath', step: 'stepSoft' },
    tameable: null,
    rideable: false, breedItem: null, babyScale: 0.5,
    fireImmune: false, waterMob: false, flying: true, avoidsSun: false,
    special: null,
  },

  // ---- ALLAY ---------------------------------------------------------------
  {
    id: 'allay',
    category: 'passive',
    model: 'allay',
    skin: 'allay',
    variants: 1,
    health: 20, armor: 0,
    width: 0.35, height: 0.6,
    speed: 0.6,
    attack: null,
    followRange: 32, xp: [3, 6],
    drops: [],
    spawn: null, // found in pillager outposts / woodland mansions; not naturally spawned
    ai: ['wander', 'lookAround', 'followOwner', 'custom:allay'],
    sounds: { idle: 'allayIdle', hurt: 'allayHurt', death: 'allayDeath', step: 'stepSoft' },
    tameable: null,
    rideable: false, breedItem: null, babyScale: 0.5,
    fireImmune: false, waterMob: false, flying: true, avoidsSun: false,
    special: null,
  },
];
